;; Generated by :claw at Fri Nov  7 13:13:12 2025 +0530
(uiop:define-package "CLAW-CXX-GLFW3" (:use))
(uiop:define-package :claw-cxx-glfw3-bindings~pristine (:use :cl))
(common-lisp:in-package :claw-cxx-glfw3-bindings~pristine)

(defparameter claw-cxx-glfw3::+glfwapi+ ())

(defparameter claw-cxx-glfw3::+accum-alpha-bits+ 135178)

(defparameter claw-cxx-glfw3::+accum-blue-bits+ 135177)

(defparameter claw-cxx-glfw3::+accum-green-bits+ 135176)

(defparameter claw-cxx-glfw3::+accum-red-bits+ 135175)

(defparameter claw-cxx-glfw3::+alpha-bits+ 135172)

(defparameter claw-cxx-glfw3::+angle-platform-type+ 327682)

(defparameter claw-cxx-glfw3::+angle-platform-type-d3d11+ 225285)

(defparameter claw-cxx-glfw3::+angle-platform-type-d3d9+ 225284)

(defparameter claw-cxx-glfw3::+angle-platform-type-metal+ 225288)

(defparameter claw-cxx-glfw3::+angle-platform-type-none+ 225281)

(defparameter claw-cxx-glfw3::+angle-platform-type-opengl+ 225282)

(defparameter claw-cxx-glfw3::+angle-platform-type-opengles+ 225283)

(defparameter claw-cxx-glfw3::+angle-platform-type-vulkan+ 225287)

(defparameter claw-cxx-glfw3::+any-platform+ 393216)

(defparameter claw-cxx-glfw3::+any-position+ 2147483648)

(defparameter claw-cxx-glfw3::+any-release-behavior+ 0)

(defparameter claw-cxx-glfw3::+apientry-defined+ ())

(defparameter claw-cxx-glfw3::+api-unavailable+ 65542)

(defparameter claw-cxx-glfw3::+arrow-cursor+ 221185)

(defparameter claw-cxx-glfw3::+auto-iconify+ 131078)

(defparameter claw-cxx-glfw3::+aux-buffers+ 135179)

(defparameter claw-cxx-glfw3::+blue-bits+ 135171)

(defparameter claw-cxx-glfw3::+center-cursor+ 131081)

(defparameter claw-cxx-glfw3::+client-api+ 139265)

(defparameter claw-cxx-glfw3::+cocoa-chdir-resources+ 331777)

(defparameter claw-cxx-glfw3::+cocoa-frame-name+ 143362)

(defparameter claw-cxx-glfw3::+cocoa-graphics-switching+ 143363)

(defparameter claw-cxx-glfw3::+cocoa-menubar+ 331778)

(defparameter claw-cxx-glfw3::+cocoa-retina-framebuffer+ 143361)

(defparameter claw-cxx-glfw3::+connected+ 262145)

(defparameter claw-cxx-glfw3::+context-creation-api+ 139275)

(defparameter claw-cxx-glfw3::+context-debug+ 139271)

(defparameter claw-cxx-glfw3::+context-no-error+ 139274)

(defparameter claw-cxx-glfw3::+context-release-behavior+ 139273)

(defparameter claw-cxx-glfw3::+context-revision+ 139268)

(defparameter claw-cxx-glfw3::+context-robustness+ 139269)

(defparameter claw-cxx-glfw3::+context-version-major+ 139266)

(defparameter claw-cxx-glfw3::+context-version-minor+ 139267)

(defparameter claw-cxx-glfw3::+crosshair-cursor+ 221187)

(defparameter claw-cxx-glfw3::+cursor+ 208897)

(defparameter claw-cxx-glfw3::+cursor-captured+ 212996)

(defparameter claw-cxx-glfw3::+cursor-disabled+ 212995)

(defparameter claw-cxx-glfw3::+cursor-hidden+ 212994)

(defparameter claw-cxx-glfw3::+cursor-normal+ 212993)

(defparameter claw-cxx-glfw3::+cursor-unavailable+ 65547)

(defparameter claw-cxx-glfw3::+decorated+ 131077)

(defparameter claw-cxx-glfw3::+depth-bits+ 135173)

(defparameter claw-cxx-glfw3::+disconnected+ 262146)

(defparameter claw-cxx-glfw3::+dont-care+ -1)

(defparameter claw-cxx-glfw3::+doublebuffer+ 135184)

(defparameter claw-cxx-glfw3::+egl-context-api+ 221186)

(defparameter claw-cxx-glfw3::+false+ 0)

(defparameter claw-cxx-glfw3::+feature-unavailable+ 65548)

(defparameter claw-cxx-glfw3::+feature-unimplemented+ 65549)

(defparameter claw-cxx-glfw3::+floating+ 131079)

(defparameter claw-cxx-glfw3::+focused+ 131073)

(defparameter claw-cxx-glfw3::+focus-on-show+ 131084)

(defparameter claw-cxx-glfw3::+format-unavailable+ 65545)

(defparameter claw-cxx-glfw3::+gamepad-axis-last+ 5)

(defparameter claw-cxx-glfw3::+gamepad-axis-left-trigger+ 4)

(defparameter claw-cxx-glfw3::+gamepad-axis-left-x+ 0)

(defparameter claw-cxx-glfw3::+gamepad-axis-left-y+ 1)

(defparameter claw-cxx-glfw3::+gamepad-axis-right-trigger+ 5)

(defparameter claw-cxx-glfw3::+gamepad-axis-right-x+ 2)

(defparameter claw-cxx-glfw3::+gamepad-axis-right-y+ 3)

(defparameter claw-cxx-glfw3::+gamepad-button-a+ 0)

(defparameter claw-cxx-glfw3::+gamepad-button-b+ 1)

(defparameter claw-cxx-glfw3::+gamepad-button-back+ 6)

(defparameter claw-cxx-glfw3::+gamepad-button-circle+ 1)

(defparameter claw-cxx-glfw3::+gamepad-button-cross+ 0)

(defparameter claw-cxx-glfw3::+gamepad-button-dpad-down+ 13)

(defparameter claw-cxx-glfw3::+gamepad-button-dpad-left+ 14)

(defparameter claw-cxx-glfw3::+gamepad-button-dpad-right+ 12)

(defparameter claw-cxx-glfw3::+gamepad-button-dpad-up+ 11)

(defparameter claw-cxx-glfw3::+gamepad-button-guide+ 8)

(defparameter claw-cxx-glfw3::+gamepad-button-last+ 14)

(defparameter claw-cxx-glfw3::+gamepad-button-left-bumper+ 4)

(defparameter claw-cxx-glfw3::+gamepad-button-left-thumb+ 9)

(defparameter claw-cxx-glfw3::+gamepad-button-right-bumper+ 5)

(defparameter claw-cxx-glfw3::+gamepad-button-right-thumb+ 10)

(defparameter claw-cxx-glfw3::+gamepad-button-square+ 2)

(defparameter claw-cxx-glfw3::+gamepad-button-start+ 7)

(defparameter claw-cxx-glfw3::+gamepad-button-triangle+ 3)

(defparameter claw-cxx-glfw3::+gamepad-button-x+ 2)

(defparameter claw-cxx-glfw3::+gamepad-button-y+ 3)

(defparameter claw-cxx-glfw3::+green-bits+ 135170)

(defparameter claw-cxx-glfw3::+hand-cursor+ 221188)

(defparameter claw-cxx-glfw3::+hat-centered+ 0)

(defparameter claw-cxx-glfw3::+hat-down+ 4)

(defparameter claw-cxx-glfw3::+hat-left+ 8)

(defparameter claw-cxx-glfw3::+hat-left-down+ 12)

(defparameter claw-cxx-glfw3::+hat-left-up+ 9)

(defparameter claw-cxx-glfw3::+hat-right+ 2)

(defparameter claw-cxx-glfw3::+hat-right-down+ 6)

(defparameter claw-cxx-glfw3::+hat-right-up+ 3)

(defparameter claw-cxx-glfw3::+hat-up+ 1)

(defparameter claw-cxx-glfw3::+hovered+ 131083)

(defparameter claw-cxx-glfw3::+hresize-cursor+ 221189)

(defparameter claw-cxx-glfw3::+ibeam-cursor+ 221186)

(defparameter claw-cxx-glfw3::+iconified+ 131074)

(defparameter claw-cxx-glfw3::+invalid-enum+ 65539)

(defparameter claw-cxx-glfw3::+invalid-value+ 65540)

(defparameter claw-cxx-glfw3::+joystick-1+ 0)

(defparameter claw-cxx-glfw3::+joystick-10+ 9)

(defparameter claw-cxx-glfw3::+joystick-11+ 10)

(defparameter claw-cxx-glfw3::+joystick-12+ 11)

(defparameter claw-cxx-glfw3::+joystick-13+ 12)

(defparameter claw-cxx-glfw3::+joystick-14+ 13)

(defparameter claw-cxx-glfw3::+joystick-15+ 14)

(defparameter claw-cxx-glfw3::+joystick-16+ 15)

(defparameter claw-cxx-glfw3::+joystick-2+ 1)

(defparameter claw-cxx-glfw3::+joystick-3+ 2)

(defparameter claw-cxx-glfw3::+joystick-4+ 3)

(defparameter claw-cxx-glfw3::+joystick-5+ 4)

(defparameter claw-cxx-glfw3::+joystick-6+ 5)

(defparameter claw-cxx-glfw3::+joystick-7+ 6)

(defparameter claw-cxx-glfw3::+joystick-8+ 7)

(defparameter claw-cxx-glfw3::+joystick-9+ 8)

(defparameter claw-cxx-glfw3::+joystick-hat-buttons+ 327681)

(defparameter claw-cxx-glfw3::+joystick-last+ 15)

(defparameter claw-cxx-glfw3::+key-0+ 48)

(defparameter claw-cxx-glfw3::+key-1+ 49)

(defparameter claw-cxx-glfw3::+key-2+ 50)

(defparameter claw-cxx-glfw3::+key-3+ 51)

(defparameter claw-cxx-glfw3::+key-4+ 52)

(defparameter claw-cxx-glfw3::+key-5+ 53)

(defparameter claw-cxx-glfw3::+key-6+ 54)

(defparameter claw-cxx-glfw3::+key-7+ 55)

(defparameter claw-cxx-glfw3::+key-8+ 56)

(defparameter claw-cxx-glfw3::+key-9+ 57)

(defparameter claw-cxx-glfw3::+key-a+ 65)

(defparameter claw-cxx-glfw3::+key-apostrophe+ 39)

(defparameter claw-cxx-glfw3::+key-b+ 66)

(defparameter claw-cxx-glfw3::+key-backslash+ 92)

(defparameter claw-cxx-glfw3::+key-backspace+ 259)

(defparameter claw-cxx-glfw3::+key-c+ 67)

(defparameter claw-cxx-glfw3::+key-caps-lock+ 280)

(defparameter claw-cxx-glfw3::+key-comma+ 44)

(defparameter claw-cxx-glfw3::+key-d+ 68)

(defparameter claw-cxx-glfw3::+key-delete+ 261)

(defparameter claw-cxx-glfw3::+key-down+ 264)

(defparameter claw-cxx-glfw3::+key-e+ 69)

(defparameter claw-cxx-glfw3::+key-end+ 269)

(defparameter claw-cxx-glfw3::+key-enter+ 257)

(defparameter claw-cxx-glfw3::+key-equal+ 61)

(defparameter claw-cxx-glfw3::+key-escape+ 256)

(defparameter claw-cxx-glfw3::+key-f+ 70)

(defparameter claw-cxx-glfw3::+key-f1+ 290)

(defparameter claw-cxx-glfw3::+key-f10+ 299)

(defparameter claw-cxx-glfw3::+key-f11+ 300)

(defparameter claw-cxx-glfw3::+key-f12+ 301)

(defparameter claw-cxx-glfw3::+key-f13+ 302)

(defparameter claw-cxx-glfw3::+key-f14+ 303)

(defparameter claw-cxx-glfw3::+key-f15+ 304)

(defparameter claw-cxx-glfw3::+key-f16+ 305)

(defparameter claw-cxx-glfw3::+key-f17+ 306)

(defparameter claw-cxx-glfw3::+key-f18+ 307)

(defparameter claw-cxx-glfw3::+key-f19+ 308)

(defparameter claw-cxx-glfw3::+key-f2+ 291)

(defparameter claw-cxx-glfw3::+key-f20+ 309)

(defparameter claw-cxx-glfw3::+key-f21+ 310)

(defparameter claw-cxx-glfw3::+key-f22+ 311)

(defparameter claw-cxx-glfw3::+key-f23+ 312)

(defparameter claw-cxx-glfw3::+key-f24+ 313)

(defparameter claw-cxx-glfw3::+key-f25+ 314)

(defparameter claw-cxx-glfw3::+key-f3+ 292)

(defparameter claw-cxx-glfw3::+key-f4+ 293)

(defparameter claw-cxx-glfw3::+key-f5+ 294)

(defparameter claw-cxx-glfw3::+key-f6+ 295)

(defparameter claw-cxx-glfw3::+key-f7+ 296)

(defparameter claw-cxx-glfw3::+key-f8+ 297)

(defparameter claw-cxx-glfw3::+key-f9+ 298)

(defparameter claw-cxx-glfw3::+key-g+ 71)

(defparameter claw-cxx-glfw3::+key-grave-accent+ 96)

(defparameter claw-cxx-glfw3::+key-h+ 72)

(defparameter claw-cxx-glfw3::+key-home+ 268)

(defparameter claw-cxx-glfw3::+key-i+ 73)

(defparameter claw-cxx-glfw3::+key-insert+ 260)

(defparameter claw-cxx-glfw3::+key-j+ 74)

(defparameter claw-cxx-glfw3::+key-k+ 75)

(defparameter claw-cxx-glfw3::+key-kp-0+ 320)

(defparameter claw-cxx-glfw3::+key-kp-1+ 321)

(defparameter claw-cxx-glfw3::+key-kp-2+ 322)

(defparameter claw-cxx-glfw3::+key-kp-3+ 323)

(defparameter claw-cxx-glfw3::+key-kp-4+ 324)

(defparameter claw-cxx-glfw3::+key-kp-5+ 325)

(defparameter claw-cxx-glfw3::+key-kp-6+ 326)

(defparameter claw-cxx-glfw3::+key-kp-7+ 327)

(defparameter claw-cxx-glfw3::+key-kp-8+ 328)

(defparameter claw-cxx-glfw3::+key-kp-9+ 329)

(defparameter claw-cxx-glfw3::+key-kp-add+ 334)

(defparameter claw-cxx-glfw3::+key-kp-decimal+ 330)

(defparameter claw-cxx-glfw3::+key-kp-divide+ 331)

(defparameter claw-cxx-glfw3::+key-kp-enter+ 335)

(defparameter claw-cxx-glfw3::+key-kp-equal+ 336)

(defparameter claw-cxx-glfw3::+key-kp-multiply+ 332)

(defparameter claw-cxx-glfw3::+key-kp-subtract+ 333)

(defparameter claw-cxx-glfw3::+key-l+ 76)

(defparameter claw-cxx-glfw3::+key-last+ 348)

(defparameter claw-cxx-glfw3::+key-left+ 263)

(defparameter claw-cxx-glfw3::+key-left-alt+ 342)

(defparameter claw-cxx-glfw3::+key-left-bracket+ 91)

(defparameter claw-cxx-glfw3::+key-left-control+ 341)

(defparameter claw-cxx-glfw3::+key-left-shift+ 340)

(defparameter claw-cxx-glfw3::+key-left-super+ 343)

(defparameter claw-cxx-glfw3::+key-m+ 77)

(defparameter claw-cxx-glfw3::+key-menu+ 348)

(defparameter claw-cxx-glfw3::+key-minus+ 45)

(defparameter claw-cxx-glfw3::+key-n+ 78)

(defparameter claw-cxx-glfw3::+key-num-lock+ 282)

(defparameter claw-cxx-glfw3::+key-o+ 79)

(defparameter claw-cxx-glfw3::+key-p+ 80)

(defparameter claw-cxx-glfw3::+key-page-down+ 267)

(defparameter claw-cxx-glfw3::+key-page-up+ 266)

(defparameter claw-cxx-glfw3::+key-pause+ 284)

(defparameter claw-cxx-glfw3::+key-period+ 46)

(defparameter claw-cxx-glfw3::+key-print-screen+ 283)

(defparameter claw-cxx-glfw3::+key-q+ 81)

(defparameter claw-cxx-glfw3::+key-r+ 82)

(defparameter claw-cxx-glfw3::+key-right+ 262)

(defparameter claw-cxx-glfw3::+key-right-alt+ 346)

(defparameter claw-cxx-glfw3::+key-right-bracket+ 93)

(defparameter claw-cxx-glfw3::+key-right-control+ 345)

(defparameter claw-cxx-glfw3::+key-right-shift+ 344)

(defparameter claw-cxx-glfw3::+key-right-super+ 347)

(defparameter claw-cxx-glfw3::+key-s+ 83)

(defparameter claw-cxx-glfw3::+key-scroll-lock+ 281)

(defparameter claw-cxx-glfw3::+key-semicolon+ 59)

(defparameter claw-cxx-glfw3::+key-slash+ 47)

(defparameter claw-cxx-glfw3::+key-space+ 32)

(defparameter claw-cxx-glfw3::+key-t+ 84)

(defparameter claw-cxx-glfw3::+key-tab+ 258)

(defparameter claw-cxx-glfw3::+key-u+ 85)

(defparameter claw-cxx-glfw3::+key-unknown+ -1)

(defparameter claw-cxx-glfw3::+key-up+ 265)

(defparameter claw-cxx-glfw3::+key-v+ 86)

(defparameter claw-cxx-glfw3::+key-w+ 87)

(defparameter claw-cxx-glfw3::+key-world-1+ 161)

(defparameter claw-cxx-glfw3::+key-world-2+ 162)

(defparameter claw-cxx-glfw3::+key-x+ 88)

(defparameter claw-cxx-glfw3::+key-y+ 89)

(defparameter claw-cxx-glfw3::+key-z+ 90)

(defparameter claw-cxx-glfw3::+lock-key-mods+ 208900)

(defparameter claw-cxx-glfw3::+lose-context-on-reset+ 200706)

(defparameter claw-cxx-glfw3::+maximized+ 131080)

(defparameter claw-cxx-glfw3::+mod-alt+ 4)

(defparameter claw-cxx-glfw3::+mod-caps-lock+ 16)

(defparameter claw-cxx-glfw3::+mod-control+ 2)

(defparameter claw-cxx-glfw3::+mod-num-lock+ 32)

(defparameter claw-cxx-glfw3::+mod-shift+ 1)

(defparameter claw-cxx-glfw3::+mod-super+ 8)

(defparameter claw-cxx-glfw3::+mouse-button-1+ 0)

(defparameter claw-cxx-glfw3::+mouse-button-2+ 1)

(defparameter claw-cxx-glfw3::+mouse-button-3+ 2)

(defparameter claw-cxx-glfw3::+mouse-button-4+ 3)

(defparameter claw-cxx-glfw3::+mouse-button-5+ 4)

(defparameter claw-cxx-glfw3::+mouse-button-6+ 5)

(defparameter claw-cxx-glfw3::+mouse-button-7+ 6)

(defparameter claw-cxx-glfw3::+mouse-button-8+ 7)

(defparameter claw-cxx-glfw3::+mouse-button-last+ 7)

(defparameter claw-cxx-glfw3::+mouse-button-left+ 0)

(defparameter claw-cxx-glfw3::+mouse-button-middle+ 2)

(defparameter claw-cxx-glfw3::+mouse-button-right+ 1)

(defparameter claw-cxx-glfw3::+mouse-passthrough+ 131085)

(defparameter claw-cxx-glfw3::+native-context-api+ 221185)

(defparameter claw-cxx-glfw3::+not-allowed-cursor+ 221194)

(defparameter claw-cxx-glfw3::+not-initialized+ 65537)

(defparameter claw-cxx-glfw3::+no-api+ 0)

(defparameter claw-cxx-glfw3::+no-current-context+ 65538)

(defparameter claw-cxx-glfw3::+no-error+ 0)

(defparameter claw-cxx-glfw3::+no-reset-notification+ 200705)

(defparameter claw-cxx-glfw3::+no-robustness+ 0)

(defparameter claw-cxx-glfw3::+no-window-context+ 65546)

(defparameter claw-cxx-glfw3::+opengl-any-profile+ 0)

(defparameter claw-cxx-glfw3::+opengl-api+ 196609)

(defparameter claw-cxx-glfw3::+opengl-compat-profile+ 204802)

(defparameter claw-cxx-glfw3::+opengl-core-profile+ 204801)

(defparameter claw-cxx-glfw3::+opengl-debug-context+ 139271)

(defparameter claw-cxx-glfw3::+opengl-es-api+ 196610)

(defparameter claw-cxx-glfw3::+opengl-forward-compat+ 139270)

(defparameter claw-cxx-glfw3::+opengl-profile+ 139272)

(defparameter claw-cxx-glfw3::+osmesa-context-api+ 221187)

(defparameter claw-cxx-glfw3::+out-of-memory+ 65541)

(defparameter claw-cxx-glfw3::+platform+ 327683)

(defparameter claw-cxx-glfw3::+platform-cocoa+ 393218)

(defparameter claw-cxx-glfw3::+platform-error+ 65544)

(defparameter claw-cxx-glfw3::+platform-null+ 393221)

(defparameter claw-cxx-glfw3::+platform-unavailable+ 65550)

(defparameter claw-cxx-glfw3::+platform-wayland+ 393219)

(defparameter claw-cxx-glfw3::+platform-win32+ 393217)

(defparameter claw-cxx-glfw3::+platform-x11+ 393220)

(defparameter claw-cxx-glfw3::+pointing-hand-cursor+ 221188)

(defparameter claw-cxx-glfw3::+position-x+ 131086)

(defparameter claw-cxx-glfw3::+position-y+ 131087)

(defparameter claw-cxx-glfw3::+press+ 1)

(defparameter claw-cxx-glfw3::+raw-mouse-motion+ 208901)

(defparameter claw-cxx-glfw3::+red-bits+ 135169)

(defparameter claw-cxx-glfw3::+refresh-rate+ 135183)

(defparameter claw-cxx-glfw3::+release+ 0)

(defparameter claw-cxx-glfw3::+release-behavior-flush+ 217089)

(defparameter claw-cxx-glfw3::+release-behavior-none+ 217090)

(defparameter claw-cxx-glfw3::+repeat+ 2)

(defparameter claw-cxx-glfw3::+resizable+ 131075)

(defparameter claw-cxx-glfw3::+resize-all-cursor+ 221193)

(defparameter claw-cxx-glfw3::+resize-ew-cursor+ 221189)

(defparameter claw-cxx-glfw3::+resize-nesw-cursor+ 221192)

(defparameter claw-cxx-glfw3::+resize-ns-cursor+ 221190)

(defparameter claw-cxx-glfw3::+resize-nwse-cursor+ 221191)

(defparameter claw-cxx-glfw3::+samples+ 135181)

(defparameter claw-cxx-glfw3::+scale-to-monitor+ 139276)

(defparameter claw-cxx-glfw3::+srgb-capable+ 135182)

(defparameter claw-cxx-glfw3::+stencil-bits+ 135174)

(defparameter claw-cxx-glfw3::+stereo+ 135180)

(defparameter claw-cxx-glfw3::+sticky-keys+ 208898)

(defparameter claw-cxx-glfw3::+sticky-mouse-buttons+ 208899)

(defparameter claw-cxx-glfw3::+transparent-framebuffer+ 131082)

(defparameter claw-cxx-glfw3::+true+ 1)

(defparameter claw-cxx-glfw3::+version-major+ 3)

(defparameter claw-cxx-glfw3::+version-minor+ 4)

(defparameter claw-cxx-glfw3::+version-revision+ 0)

(defparameter claw-cxx-glfw3::+version-unavailable+ 65543)

(defparameter claw-cxx-glfw3::+visible+ 131076)

(defparameter claw-cxx-glfw3::+vresize-cursor+ 221190)

(defparameter claw-cxx-glfw3::+wayland-app-id+ 155649)

(defparameter claw-cxx-glfw3::+wayland-disable-libdecor+ 229378)

(defparameter claw-cxx-glfw3::+wayland-libdecor+ 339969)

(defparameter claw-cxx-glfw3::+wayland-prefer-libdecor+ 229377)

(defparameter claw-cxx-glfw3::+win32-keyboard-menu+ 151553)

(defparameter claw-cxx-glfw3::+x11-class-name+ 147457)

(defparameter claw-cxx-glfw3::+x11-instance-name+ 147458)

(defparameter claw-cxx-glfw3::+x11-xcb-vulkan-surface+ 335873)

(defparameter claw-cxx-glfw3::+khronos-false+ 0)

(defparameter claw-cxx-glfw3::+khronos-true+ 1)

(defparameter claw-cxx-glfw3::+khronos-boolean-enum-force-size+ 2147483647)

(cffi:defcstruct (claw-cxx-glfw3::glf-wcursor :size 0))

(cffi:defctype claw-cxx-glfw3::glf-wcursor
               (:struct claw-cxx-glfw3::glf-wcursor))

(cffi:defcstruct (claw-cxx-glfw3::glf-wimage :size 16)
  (claw-cxx-glfw3::width :int :offset 0)
  (claw-cxx-glfw3::height :int :offset 4)
  (claw-cxx-glfw3::pixels (:pointer :unsigned-char) :offset 8))

(cffi:defctype claw-cxx-glfw3::glf-wimage
               (:struct claw-cxx-glfw3::glf-wimage))

(declaim (inline claw-cxx-glfw3::create-cursor))

(cffi:defcfun ("glfwCreateCursor" claw-cxx-glfw3::create-cursor)
              (:pointer claw-cxx-glfw3::glf-wcursor)
  (claw-cxx-glfw3::image (:pointer claw-cxx-glfw3::glf-wimage))
  (claw-cxx-glfw3::xhot :int)
  (claw-cxx-glfw3::yhot :int))

(declaim (inline claw-cxx-glfw3::create-standard-cursor))

(cffi:defcfun ("glfwCreateStandardCursor"
               claw-cxx-glfw3::create-standard-cursor)
              (:pointer claw-cxx-glfw3::glf-wcursor)
  (claw-cxx-glfw3::shape :int))

(cffi:defcstruct (claw-cxx-glfw3::glf-wmonitor :size 0))

(cffi:defctype claw-cxx-glfw3::glf-wmonitor
               (:struct claw-cxx-glfw3::glf-wmonitor))

(cffi:defcstruct (claw-cxx-glfw3::glf-wwindow :size 0))

(cffi:defctype claw-cxx-glfw3::glf-wwindow
               (:struct claw-cxx-glfw3::glf-wwindow))

(declaim (inline claw-cxx-glfw3::create-window))

(cffi:defcfun ("glfwCreateWindow" claw-cxx-glfw3::create-window)
              (:pointer claw-cxx-glfw3::glf-wwindow)
  (claw-cxx-glfw3::width :int)
  (claw-cxx-glfw3::height :int)
  (claw-cxx-glfw3::title :string)
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::share (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::default-window-hints))

(cffi:defcfun ("glfwDefaultWindowHints"
               claw-cxx-glfw3::default-window-hints)
              :void)

(declaim (inline claw-cxx-glfw3::destroy-cursor))

(cffi:defcfun ("glfwDestroyCursor" claw-cxx-glfw3::destroy-cursor)
              :void
  (claw-cxx-glfw3::cursor (:pointer claw-cxx-glfw3::glf-wcursor)))

(declaim (inline claw-cxx-glfw3::destroy-window))

(cffi:defcfun ("glfwDestroyWindow" claw-cxx-glfw3::destroy-window)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::extension-supported))

(cffi:defcfun ("glfwExtensionSupported"
               claw-cxx-glfw3::extension-supported)
              :int
  (claw-cxx-glfw3::extension :string))

(declaim (inline claw-cxx-glfw3::focus-window))

(cffi:defcfun ("glfwFocusWindow" claw-cxx-glfw3::focus-window) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::get-clipboard-string))

(cffi:defcfun ("glfwGetClipboardString"
               claw-cxx-glfw3::get-clipboard-string)
              :string
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::get-current-context))

(cffi:defcfun ("glfwGetCurrentContext"
               claw-cxx-glfw3::get-current-context)
              (:pointer claw-cxx-glfw3::glf-wwindow))

(declaim (inline claw-cxx-glfw3::get-cursor-pos))

(cffi:defcfun ("glfwGetCursorPos" claw-cxx-glfw3::get-cursor-pos) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::xpos (:pointer :double))
  (claw-cxx-glfw3::ypos (:pointer :double)))

(declaim (inline claw-cxx-glfw3::get-error))

(cffi:defcfun ("glfwGetError" claw-cxx-glfw3::get-error) :int
  (claw-cxx-glfw3::description (:pointer :string)))

(declaim (inline claw-cxx-glfw3::get-framebuffer-size))

(cffi:defcfun ("glfwGetFramebufferSize"
               claw-cxx-glfw3::get-framebuffer-size)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::width (:pointer :int))
  (claw-cxx-glfw3::height (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-gamepad-name))

(cffi:defcfun ("glfwGetGamepadName" claw-cxx-glfw3::get-gamepad-name)
              :string
  (claw-cxx-glfw3::jid :int))

(cffi:defcstruct (claw-cxx-glfw3::glf-wgamepadstate :size 40)
  (claw-cxx-glfw3::buttons :unsigned-char :count 15 :offset 0)
  (claw-cxx-glfw3::axes :float :count 6 :offset 16))

(cffi:defctype claw-cxx-glfw3::glf-wgamepadstate
               (:struct claw-cxx-glfw3::glf-wgamepadstate))

(declaim (inline claw-cxx-glfw3::get-gamepad-state))

(cffi:defcfun ("glfwGetGamepadState" claw-cxx-glfw3::get-gamepad-state)
              :int
  (claw-cxx-glfw3::jid :int)
  (claw-cxx-glfw3::state (:pointer claw-cxx-glfw3::glf-wgamepadstate)))

(cffi:defcstruct (claw-cxx-glfw3::glf-wgammaramp :size 32)
  (claw-cxx-glfw3::red (:pointer :unsigned-short) :offset 0)
  (claw-cxx-glfw3::green (:pointer :unsigned-short) :offset 8)
  (claw-cxx-glfw3::blue (:pointer :unsigned-short) :offset 16)
  (claw-cxx-glfw3::size :unsigned-int :offset 24))

(cffi:defctype claw-cxx-glfw3::glf-wgammaramp
               (:struct claw-cxx-glfw3::glf-wgammaramp))

(declaim (inline claw-cxx-glfw3::get-gamma-ramp))

(cffi:defcfun ("glfwGetGammaRamp" claw-cxx-glfw3::get-gamma-ramp)
              (:pointer claw-cxx-glfw3::glf-wgammaramp)
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor)))

(declaim (inline claw-cxx-glfw3::get-input-mode))

(cffi:defcfun ("glfwGetInputMode" claw-cxx-glfw3::get-input-mode) :int
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::mode :int))

(declaim (inline claw-cxx-glfw3::get-joystick-axes))

(cffi:defcfun ("glfwGetJoystickAxes" claw-cxx-glfw3::get-joystick-axes)
              (:pointer :float)
  (claw-cxx-glfw3::jid :int)
  (claw-cxx-glfw3::count (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-joystick-buttons))

(cffi:defcfun ("glfwGetJoystickButtons"
               claw-cxx-glfw3::get-joystick-buttons)
              (:pointer :unsigned-char)
  (claw-cxx-glfw3::jid :int)
  (claw-cxx-glfw3::count (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-joystick-guid))

(cffi:defcfun ("glfwGetJoystickGUID" claw-cxx-glfw3::get-joystick-guid)
              :string
  (claw-cxx-glfw3::jid :int))

(declaim (inline claw-cxx-glfw3::get-joystick-hats))

(cffi:defcfun ("glfwGetJoystickHats" claw-cxx-glfw3::get-joystick-hats)
              (:pointer :unsigned-char)
  (claw-cxx-glfw3::jid :int)
  (claw-cxx-glfw3::count (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-joystick-name))

(cffi:defcfun ("glfwGetJoystickName" claw-cxx-glfw3::get-joystick-name)
              :string
  (claw-cxx-glfw3::jid :int))

(declaim (inline claw-cxx-glfw3::get-joystick-user-pointer))

(cffi:defcfun ("glfwGetJoystickUserPointer"
               claw-cxx-glfw3::get-joystick-user-pointer)
              (:pointer :void)
  (claw-cxx-glfw3::jid :int))

(declaim (inline claw-cxx-glfw3::get-key))

(cffi:defcfun ("glfwGetKey" claw-cxx-glfw3::get-key) :int
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::key :int))

(declaim (inline claw-cxx-glfw3::get-key-name))

(cffi:defcfun ("glfwGetKeyName" claw-cxx-glfw3::get-key-name) :string
  (claw-cxx-glfw3::key :int)
  (claw-cxx-glfw3::scancode :int))

(declaim (inline claw-cxx-glfw3::get-key-scancode))

(cffi:defcfun ("glfwGetKeyScancode" claw-cxx-glfw3::get-key-scancode)
              :int
  (claw-cxx-glfw3::key :int))

(declaim (inline claw-cxx-glfw3::get-monitor-content-scale))

(cffi:defcfun ("glfwGetMonitorContentScale"
               claw-cxx-glfw3::get-monitor-content-scale)
              :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::xscale (:pointer :float))
  (claw-cxx-glfw3::yscale (:pointer :float)))

(declaim (inline claw-cxx-glfw3::get-monitor-name))

(cffi:defcfun ("glfwGetMonitorName" claw-cxx-glfw3::get-monitor-name)
              :string
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor)))

(declaim (inline claw-cxx-glfw3::get-monitor-physical-size))

(cffi:defcfun ("glfwGetMonitorPhysicalSize"
               claw-cxx-glfw3::get-monitor-physical-size)
              :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::width-mm (:pointer :int))
  (claw-cxx-glfw3::height-mm (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-monitor-pos))

(cffi:defcfun ("glfwGetMonitorPos" claw-cxx-glfw3::get-monitor-pos)
              :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::xpos (:pointer :int))
  (claw-cxx-glfw3::ypos (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-monitor-user-pointer))

(cffi:defcfun ("glfwGetMonitorUserPointer"
               claw-cxx-glfw3::get-monitor-user-pointer)
              (:pointer :void)
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor)))

(declaim (inline claw-cxx-glfw3::get-monitor-workarea))

(cffi:defcfun ("glfwGetMonitorWorkarea"
               claw-cxx-glfw3::get-monitor-workarea)
              :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::xpos (:pointer :int))
  (claw-cxx-glfw3::ypos (:pointer :int))
  (claw-cxx-glfw3::width (:pointer :int))
  (claw-cxx-glfw3::height (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-monitors))

(cffi:defcfun ("glfwGetMonitors" claw-cxx-glfw3::get-monitors)
              (:pointer (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::count (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-mouse-button))

(cffi:defcfun ("glfwGetMouseButton" claw-cxx-glfw3::get-mouse-button)
              :int
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::button :int))

(declaim (inline claw-cxx-glfw3::get-platform))

(cffi:defcfun ("glfwGetPlatform" claw-cxx-glfw3::get-platform) :int)

(declaim (inline claw-cxx-glfw3::get-primary-monitor))

(cffi:defcfun ("glfwGetPrimaryMonitor"
               claw-cxx-glfw3::get-primary-monitor)
              (:pointer claw-cxx-glfw3::glf-wmonitor))

(cffi:defctype claw-cxx-glfw3::glf-wglproc (:pointer :void))

(declaim (inline claw-cxx-glfw3::get-proc-address))

(cffi:defcfun ("glfwGetProcAddress" claw-cxx-glfw3::get-proc-address)
              claw-cxx-glfw3::glf-wglproc
  (claw-cxx-glfw3::procname :string))

(cffi:defctype claw-cxx-glfw3::uint32-t :unsigned-int)

(declaim (inline claw-cxx-glfw3::get-required-instance-extensions))

(cffi:defcfun ("glfwGetRequiredInstanceExtensions"
               claw-cxx-glfw3::get-required-instance-extensions)
              (:pointer :string)
  (claw-cxx-glfw3::count (:pointer claw-cxx-glfw3::uint32-t)))

(declaim (inline claw-cxx-glfw3::get-time))

(cffi:defcfun ("glfwGetTime" claw-cxx-glfw3::get-time) :double)

(cffi:defctype claw-cxx-glfw3::uint64-t :unsigned-long)

(declaim (inline claw-cxx-glfw3::get-timer-frequency))

(cffi:defcfun ("glfwGetTimerFrequency"
               claw-cxx-glfw3::get-timer-frequency)
              claw-cxx-glfw3::uint64-t)

(declaim (inline claw-cxx-glfw3::get-timer-value))

(cffi:defcfun ("glfwGetTimerValue" claw-cxx-glfw3::get-timer-value)
              claw-cxx-glfw3::uint64-t)

(declaim (inline claw-cxx-glfw3::get-version))

(cffi:defcfun ("glfwGetVersion" claw-cxx-glfw3::get-version) :void
  (claw-cxx-glfw3::major (:pointer :int))
  (claw-cxx-glfw3::minor (:pointer :int))
  (claw-cxx-glfw3::rev (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-version-string))

(cffi:defcfun ("glfwGetVersionString"
               claw-cxx-glfw3::get-version-string)
              :string)

(cffi:defcstruct (claw-cxx-glfw3::glf-wvidmode :size 24)
  (claw-cxx-glfw3::width :int :offset 0)
  (claw-cxx-glfw3::height :int :offset 4)
  (claw-cxx-glfw3::red-bits :int :offset 8)
  (claw-cxx-glfw3::green-bits :int :offset 12)
  (claw-cxx-glfw3::blue-bits :int :offset 16)
  (claw-cxx-glfw3::refresh-rate :int :offset 20))

(cffi:defctype claw-cxx-glfw3::glf-wvidmode
               (:struct claw-cxx-glfw3::glf-wvidmode))

(declaim (inline claw-cxx-glfw3::get-video-mode))

(cffi:defcfun ("glfwGetVideoMode" claw-cxx-glfw3::get-video-mode)
              (:pointer claw-cxx-glfw3::glf-wvidmode)
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor)))

(declaim (inline claw-cxx-glfw3::get-video-modes))

(cffi:defcfun ("glfwGetVideoModes" claw-cxx-glfw3::get-video-modes)
              (:pointer claw-cxx-glfw3::glf-wvidmode)
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::count (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-window-attrib))

(cffi:defcfun ("glfwGetWindowAttrib" claw-cxx-glfw3::get-window-attrib)
              :int
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::attrib :int))

(declaim (inline claw-cxx-glfw3::get-window-content-scale))

(cffi:defcfun ("glfwGetWindowContentScale"
               claw-cxx-glfw3::get-window-content-scale)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::xscale (:pointer :float))
  (claw-cxx-glfw3::yscale (:pointer :float)))

(declaim (inline claw-cxx-glfw3::get-window-frame-size))

(cffi:defcfun ("glfwGetWindowFrameSize"
               claw-cxx-glfw3::get-window-frame-size)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::left (:pointer :int))
  (claw-cxx-glfw3::top (:pointer :int))
  (claw-cxx-glfw3::right (:pointer :int))
  (claw-cxx-glfw3::bottom (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-window-monitor))

(cffi:defcfun ("glfwGetWindowMonitor"
               claw-cxx-glfw3::get-window-monitor)
              (:pointer claw-cxx-glfw3::glf-wmonitor)
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::get-window-opacity))

(cffi:defcfun ("glfwGetWindowOpacity"
               claw-cxx-glfw3::get-window-opacity)
              :float
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::get-window-pos))

(cffi:defcfun ("glfwGetWindowPos" claw-cxx-glfw3::get-window-pos) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::xpos (:pointer :int))
  (claw-cxx-glfw3::ypos (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-window-size))

(cffi:defcfun ("glfwGetWindowSize" claw-cxx-glfw3::get-window-size)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::width (:pointer :int))
  (claw-cxx-glfw3::height (:pointer :int)))

(declaim (inline claw-cxx-glfw3::get-window-user-pointer))

(cffi:defcfun ("glfwGetWindowUserPointer"
               claw-cxx-glfw3::get-window-user-pointer)
              (:pointer :void)
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::hide-window))

(cffi:defcfun ("glfwHideWindow" claw-cxx-glfw3::hide-window) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::iconify-window))

(cffi:defcfun ("glfwIconifyWindow" claw-cxx-glfw3::iconify-window)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::init))

(cffi:defcfun ("glfwInit" claw-cxx-glfw3::init) :int)

(cffi:defctype claw-cxx-glfw3::glf-wallocatefun (:pointer :void))

(cffi:defctype claw-cxx-glfw3::glf-wreallocatefun (:pointer :void))

(cffi:defctype claw-cxx-glfw3::glf-wdeallocatefun (:pointer :void))

(cffi:defcstruct (claw-cxx-glfw3::glf-wallocator :size 32)
  (claw-cxx-glfw3::allocate claw-cxx-glfw3::glf-wallocatefun :offset 0)
  (claw-cxx-glfw3::reallocate
   claw-cxx-glfw3::glf-wreallocatefun
   :offset
   8)
  (claw-cxx-glfw3::deallocate
   claw-cxx-glfw3::glf-wdeallocatefun
   :offset
   16)
  (claw-cxx-glfw3::user (:pointer :void) :offset 24))

(cffi:defctype claw-cxx-glfw3::glf-wallocator
               (:struct claw-cxx-glfw3::glf-wallocator))

(declaim (inline claw-cxx-glfw3::init-allocator))

(cffi:defcfun ("glfwInitAllocator" claw-cxx-glfw3::init-allocator)
              :void
  (claw-cxx-glfw3::allocator (:pointer claw-cxx-glfw3::glf-wallocator)))

(declaim (inline claw-cxx-glfw3::init-hint))

(cffi:defcfun ("glfwInitHint" claw-cxx-glfw3::init-hint) :void
  (claw-cxx-glfw3::hint :int)
  (claw-cxx-glfw3::value :int))

(declaim (inline claw-cxx-glfw3::joystick-is-gamepad))

(cffi:defcfun ("glfwJoystickIsGamepad"
               claw-cxx-glfw3::joystick-is-gamepad)
              :int
  (claw-cxx-glfw3::jid :int))

(declaim (inline claw-cxx-glfw3::joystick-present))

(cffi:defcfun ("glfwJoystickPresent" claw-cxx-glfw3::joystick-present)
              :int
  (claw-cxx-glfw3::jid :int))

(declaim (inline claw-cxx-glfw3::make-context-current))

(cffi:defcfun ("glfwMakeContextCurrent"
               claw-cxx-glfw3::make-context-current)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::maximize-window))

(cffi:defcfun ("glfwMaximizeWindow" claw-cxx-glfw3::maximize-window)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::platform-supported))

(cffi:defcfun ("glfwPlatformSupported"
               claw-cxx-glfw3::platform-supported)
              :int
  (claw-cxx-glfw3::platform :int))

(declaim (inline claw-cxx-glfw3::poll-events))

(cffi:defcfun ("glfwPollEvents" claw-cxx-glfw3::poll-events) :void)

(declaim (inline claw-cxx-glfw3::post-empty-event))

(cffi:defcfun ("glfwPostEmptyEvent" claw-cxx-glfw3::post-empty-event)
              :void)

(declaim (inline claw-cxx-glfw3::raw-mouse-motion-supported))

(cffi:defcfun ("glfwRawMouseMotionSupported"
               claw-cxx-glfw3::raw-mouse-motion-supported)
              :int)

(declaim (inline claw-cxx-glfw3::request-window-attention))

(cffi:defcfun ("glfwRequestWindowAttention"
               claw-cxx-glfw3::request-window-attention)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::restore-window))

(cffi:defcfun ("glfwRestoreWindow" claw-cxx-glfw3::restore-window)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(cffi:defctype claw-cxx-glfw3::glf-wcharfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-char-callback))

(cffi:defcfun ("glfwSetCharCallback" claw-cxx-glfw3::set-char-callback)
              claw-cxx-glfw3::glf-wcharfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wcharfun))

(cffi:defctype claw-cxx-glfw3::glf-wcharmodsfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-char-mods-callback))

(cffi:defcfun ("glfwSetCharModsCallback"
               claw-cxx-glfw3::set-char-mods-callback)
              claw-cxx-glfw3::glf-wcharmodsfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wcharmodsfun))

(declaim (inline claw-cxx-glfw3::set-clipboard-string))

(cffi:defcfun ("glfwSetClipboardString"
               claw-cxx-glfw3::set-clipboard-string)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::string :string))

(declaim (inline claw-cxx-glfw3::set-cursor))

(cffi:defcfun ("glfwSetCursor" claw-cxx-glfw3::set-cursor) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::cursor (:pointer claw-cxx-glfw3::glf-wcursor)))

(cffi:defctype claw-cxx-glfw3::glf-wcursorenterfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-cursor-enter-callback))

(cffi:defcfun ("glfwSetCursorEnterCallback"
               claw-cxx-glfw3::set-cursor-enter-callback)
              claw-cxx-glfw3::glf-wcursorenterfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wcursorenterfun))

(declaim (inline claw-cxx-glfw3::set-cursor-pos))

(cffi:defcfun ("glfwSetCursorPos" claw-cxx-glfw3::set-cursor-pos) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::xpos :double)
  (claw-cxx-glfw3::ypos :double))

(cffi:defctype claw-cxx-glfw3::glf-wcursorposfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-cursor-pos-callback))

(cffi:defcfun ("glfwSetCursorPosCallback"
               claw-cxx-glfw3::set-cursor-pos-callback)
              claw-cxx-glfw3::glf-wcursorposfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wcursorposfun))

(cffi:defctype claw-cxx-glfw3::glf-wdropfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-drop-callback))

(cffi:defcfun ("glfwSetDropCallback" claw-cxx-glfw3::set-drop-callback)
              claw-cxx-glfw3::glf-wdropfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wdropfun))

(cffi:defctype claw-cxx-glfw3::glf-werrorfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-error-callback))

(cffi:defcfun ("glfwSetErrorCallback"
               claw-cxx-glfw3::set-error-callback)
              claw-cxx-glfw3::glf-werrorfun
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-werrorfun))

(cffi:defctype claw-cxx-glfw3::glf-wframebuffersizefun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-framebuffer-size-callback))

(cffi:defcfun ("glfwSetFramebufferSizeCallback"
               claw-cxx-glfw3::set-framebuffer-size-callback)
              claw-cxx-glfw3::glf-wframebuffersizefun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wframebuffersizefun))

(declaim (inline claw-cxx-glfw3::set-gamma))

(cffi:defcfun ("glfwSetGamma" claw-cxx-glfw3::set-gamma) :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::gamma :float))

(declaim (inline claw-cxx-glfw3::set-gamma-ramp))

(cffi:defcfun ("glfwSetGammaRamp" claw-cxx-glfw3::set-gamma-ramp) :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::ramp (:pointer claw-cxx-glfw3::glf-wgammaramp)))

(declaim (inline claw-cxx-glfw3::set-input-mode))

(cffi:defcfun ("glfwSetInputMode" claw-cxx-glfw3::set-input-mode) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::mode :int)
  (claw-cxx-glfw3::value :int))

(cffi:defctype claw-cxx-glfw3::glf-wjoystickfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-joystick-callback))

(cffi:defcfun ("glfwSetJoystickCallback"
               claw-cxx-glfw3::set-joystick-callback)
              claw-cxx-glfw3::glf-wjoystickfun
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wjoystickfun))

(declaim (inline claw-cxx-glfw3::set-joystick-user-pointer))

(cffi:defcfun ("glfwSetJoystickUserPointer"
               claw-cxx-glfw3::set-joystick-user-pointer)
              :void
  (claw-cxx-glfw3::jid :int)
  (claw-cxx-glfw3::pointer (:pointer :void)))

(cffi:defctype claw-cxx-glfw3::glf-wkeyfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-key-callback))

(cffi:defcfun ("glfwSetKeyCallback" claw-cxx-glfw3::set-key-callback)
              claw-cxx-glfw3::glf-wkeyfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wkeyfun))

(cffi:defctype claw-cxx-glfw3::glf-wmonitorfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-monitor-callback))

(cffi:defcfun ("glfwSetMonitorCallback"
               claw-cxx-glfw3::set-monitor-callback)
              claw-cxx-glfw3::glf-wmonitorfun
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wmonitorfun))

(declaim (inline claw-cxx-glfw3::set-monitor-user-pointer))

(cffi:defcfun ("glfwSetMonitorUserPointer"
               claw-cxx-glfw3::set-monitor-user-pointer)
              :void
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::pointer (:pointer :void)))

(cffi:defctype claw-cxx-glfw3::glf-wmousebuttonfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-mouse-button-callback))

(cffi:defcfun ("glfwSetMouseButtonCallback"
               claw-cxx-glfw3::set-mouse-button-callback)
              claw-cxx-glfw3::glf-wmousebuttonfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wmousebuttonfun))

(cffi:defctype claw-cxx-glfw3::glf-wscrollfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-scroll-callback))

(cffi:defcfun ("glfwSetScrollCallback"
               claw-cxx-glfw3::set-scroll-callback)
              claw-cxx-glfw3::glf-wscrollfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wscrollfun))

(declaim (inline claw-cxx-glfw3::set-time))

(cffi:defcfun ("glfwSetTime" claw-cxx-glfw3::set-time) :void
  (claw-cxx-glfw3::time :double))

(declaim (inline claw-cxx-glfw3::set-window-aspect-ratio))

(cffi:defcfun ("glfwSetWindowAspectRatio"
               claw-cxx-glfw3::set-window-aspect-ratio)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::numer :int)
  (claw-cxx-glfw3::denom :int))

(declaim (inline claw-cxx-glfw3::set-window-attrib))

(cffi:defcfun ("glfwSetWindowAttrib" claw-cxx-glfw3::set-window-attrib)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::attrib :int)
  (claw-cxx-glfw3::value :int))

(cffi:defctype claw-cxx-glfw3::glf-wwindowclosefun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-close-callback))

(cffi:defcfun ("glfwSetWindowCloseCallback"
               claw-cxx-glfw3::set-window-close-callback)
              claw-cxx-glfw3::glf-wwindowclosefun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowclosefun))

(cffi:defctype claw-cxx-glfw3::glf-wwindowcontentscalefun
               (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-content-scale-callback))

(cffi:defcfun ("glfwSetWindowContentScaleCallback"
               claw-cxx-glfw3::set-window-content-scale-callback)
              claw-cxx-glfw3::glf-wwindowcontentscalefun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowcontentscalefun))

(cffi:defctype claw-cxx-glfw3::glf-wwindowfocusfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-focus-callback))

(cffi:defcfun ("glfwSetWindowFocusCallback"
               claw-cxx-glfw3::set-window-focus-callback)
              claw-cxx-glfw3::glf-wwindowfocusfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowfocusfun))

(declaim (inline claw-cxx-glfw3::set-window-icon))

(cffi:defcfun ("glfwSetWindowIcon" claw-cxx-glfw3::set-window-icon)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::count :int)
  (claw-cxx-glfw3::images (:pointer claw-cxx-glfw3::glf-wimage)))

(cffi:defctype claw-cxx-glfw3::glf-wwindowiconifyfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-iconify-callback))

(cffi:defcfun ("glfwSetWindowIconifyCallback"
               claw-cxx-glfw3::set-window-iconify-callback)
              claw-cxx-glfw3::glf-wwindowiconifyfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowiconifyfun))

(cffi:defctype claw-cxx-glfw3::glf-wwindowmaximizefun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-maximize-callback))

(cffi:defcfun ("glfwSetWindowMaximizeCallback"
               claw-cxx-glfw3::set-window-maximize-callback)
              claw-cxx-glfw3::glf-wwindowmaximizefun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowmaximizefun))

(declaim (inline claw-cxx-glfw3::set-window-monitor))

(cffi:defcfun ("glfwSetWindowMonitor"
               claw-cxx-glfw3::set-window-monitor)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::monitor (:pointer claw-cxx-glfw3::glf-wmonitor))
  (claw-cxx-glfw3::xpos :int)
  (claw-cxx-glfw3::ypos :int)
  (claw-cxx-glfw3::width :int)
  (claw-cxx-glfw3::height :int)
  (claw-cxx-glfw3::refresh-rate :int))

(declaim (inline claw-cxx-glfw3::set-window-opacity))

(cffi:defcfun ("glfwSetWindowOpacity"
               claw-cxx-glfw3::set-window-opacity)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::opacity :float))

(declaim (inline claw-cxx-glfw3::set-window-pos))

(cffi:defcfun ("glfwSetWindowPos" claw-cxx-glfw3::set-window-pos) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::xpos :int)
  (claw-cxx-glfw3::ypos :int))

(cffi:defctype claw-cxx-glfw3::glf-wwindowposfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-pos-callback))

(cffi:defcfun ("glfwSetWindowPosCallback"
               claw-cxx-glfw3::set-window-pos-callback)
              claw-cxx-glfw3::glf-wwindowposfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowposfun))

(cffi:defctype claw-cxx-glfw3::glf-wwindowrefreshfun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-refresh-callback))

(cffi:defcfun ("glfwSetWindowRefreshCallback"
               claw-cxx-glfw3::set-window-refresh-callback)
              claw-cxx-glfw3::glf-wwindowrefreshfun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowrefreshfun))

(declaim (inline claw-cxx-glfw3::set-window-should-close))

(cffi:defcfun ("glfwSetWindowShouldClose"
               claw-cxx-glfw3::set-window-should-close)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::value :int))

(declaim (inline claw-cxx-glfw3::set-window-size))

(cffi:defcfun ("glfwSetWindowSize" claw-cxx-glfw3::set-window-size)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::width :int)
  (claw-cxx-glfw3::height :int))

(cffi:defctype claw-cxx-glfw3::glf-wwindowsizefun (:pointer :void))

(declaim (inline claw-cxx-glfw3::set-window-size-callback))

(cffi:defcfun ("glfwSetWindowSizeCallback"
               claw-cxx-glfw3::set-window-size-callback)
              claw-cxx-glfw3::glf-wwindowsizefun
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::callback claw-cxx-glfw3::glf-wwindowsizefun))

(declaim (inline claw-cxx-glfw3::set-window-size-limits))

(cffi:defcfun ("glfwSetWindowSizeLimits"
               claw-cxx-glfw3::set-window-size-limits)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::minwidth :int)
  (claw-cxx-glfw3::minheight :int)
  (claw-cxx-glfw3::maxwidth :int)
  (claw-cxx-glfw3::maxheight :int))

(declaim (inline claw-cxx-glfw3::set-window-title))

(cffi:defcfun ("glfwSetWindowTitle" claw-cxx-glfw3::set-window-title)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::title :string))

(declaim (inline claw-cxx-glfw3::set-window-user-pointer))

(cffi:defcfun ("glfwSetWindowUserPointer"
               claw-cxx-glfw3::set-window-user-pointer)
              :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow))
  (claw-cxx-glfw3::pointer (:pointer :void)))

(declaim (inline claw-cxx-glfw3::show-window))

(cffi:defcfun ("glfwShowWindow" claw-cxx-glfw3::show-window) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::swap-buffers))

(cffi:defcfun ("glfwSwapBuffers" claw-cxx-glfw3::swap-buffers) :void
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(declaim (inline claw-cxx-glfw3::swap-interval))

(cffi:defcfun ("glfwSwapInterval" claw-cxx-glfw3::swap-interval) :void
  (claw-cxx-glfw3::interval :int))

(declaim (inline claw-cxx-glfw3::terminate))

(cffi:defcfun ("glfwTerminate" claw-cxx-glfw3::terminate) :void)

(declaim (inline claw-cxx-glfw3::update-gamepad-mappings))

(cffi:defcfun ("glfwUpdateGamepadMappings"
               claw-cxx-glfw3::update-gamepad-mappings)
              :int
  (claw-cxx-glfw3::string :string))

(declaim (inline claw-cxx-glfw3::vulkan-supported))

(cffi:defcfun ("glfwVulkanSupported" claw-cxx-glfw3::vulkan-supported)
              :int)

(declaim (inline claw-cxx-glfw3::wait-events))

(cffi:defcfun ("glfwWaitEvents" claw-cxx-glfw3::wait-events) :void)

(declaim (inline claw-cxx-glfw3::wait-events-timeout))

(cffi:defcfun ("glfwWaitEventsTimeout"
               claw-cxx-glfw3::wait-events-timeout)
              :void
  (claw-cxx-glfw3::timeout :double))

(declaim (inline claw-cxx-glfw3::window-hint))

(cffi:defcfun ("glfwWindowHint" claw-cxx-glfw3::window-hint) :void
  (claw-cxx-glfw3::hint :int)
  (claw-cxx-glfw3::value :int))

(declaim (inline claw-cxx-glfw3::window-hint-string))

(cffi:defcfun ("glfwWindowHintString"
               claw-cxx-glfw3::window-hint-string)
              :void
  (claw-cxx-glfw3::hint :int)
  (claw-cxx-glfw3::value :string))

(declaim (inline claw-cxx-glfw3::window-should-close))

(cffi:defcfun ("glfwWindowShouldClose"
               claw-cxx-glfw3::window-should-close)
              :int
  (claw-cxx-glfw3::window (:pointer claw-cxx-glfw3::glf-wwindow)))

(cffi:defctype claw-cxx-glfw3::glf-wvkproc (:pointer :void))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export 'claw-cxx-glfw3::+khronos-false+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-core-profile+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-right-alt+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f25+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-15+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wglproc "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+feature-unavailable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+khronos-true+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wvidmode "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::init-allocator "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+khronos-boolean-enum-force-size+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-debug-context+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-right-bracket+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f3+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wallocatefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-16+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+feature-unimplemented+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::width "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wreallocatefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::height "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-es-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-right-control+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f4+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wdeallocatefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-2+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::init-hint "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+floating+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::pixels "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wallocator "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::joystick-is-gamepad "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-forward-compat+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-right-shift+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f5+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-3+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wcharfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::joystick-present "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+focused+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wcharmodsfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::make-context-current "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-profile+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-right-super+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f6+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-4+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wcursorenterfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::maximize-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+focus-on-show+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+accum-alpha-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::create-cursor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wcursorposfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::platform-supported "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+osmesa-context-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-s+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f7+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-5+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wdropfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::poll-events "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+format-unavailable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::create-standard-cursor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+accum-blue-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-werrorfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::post-empty-event "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+out-of-memory+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-scroll-lock+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f8+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-6+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wframebuffersizefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::raw-mouse-motion-supported "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-last+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+accum-green-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wjoystickfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::request-window-attention "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-semicolon+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f9+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-7+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wkeyfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::restore-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-left-trigger+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+accum-red-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wmonitorfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::create-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-cocoa+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-slash+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-g+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-8+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wmousebuttonfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-left-x+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::default-window-hints "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+alpha-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wscrollfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-char-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::destroy-cursor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-error+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-space+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-grave-accent+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowclosefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-9+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-left-y+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::destroy-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowcontentscalefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-char-mods-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-null+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-t+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-h+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowfocusfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-hat-buttons+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-right-trigger+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::extension-supported "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-d3d11+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowiconifyfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-clipboard-string "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::focus-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-unavailable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-tab+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-home+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowmaximizefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-last+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-right-x+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-cursor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-clipboard-string "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-d3d9+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowposfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-current-context "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-wayland+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-u+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-i+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowrefreshfun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-0+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-axis-right-y+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-cursor-enter-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-metal+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindowsizefun "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-cursor-pos "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-win32+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-unknown+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-insert+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wvkproc "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-1+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-a+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-cursor-pos "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-none+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-cursor-pos-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+platform-x11+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-up+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-j+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-2+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-b+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-error "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-opengl+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-drop-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-framebuffer-size "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+pointing-hand-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-v+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-k+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-3+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-back+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-opengles+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-error-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-gamepad-name "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+position-x+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-w+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-0+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-4+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-circle+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::buttons "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+angle-platform-type-vulkan+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-framebuffer-size-callback
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::axes "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+position-y+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-world-1+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-1+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-5+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-cross+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+any-platform+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-gamma "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+press+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-world-2+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-2+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-6+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-dpad-down+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-gamepad-state "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+any-position+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-gamma-ramp "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::red "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+raw-mouse-motion+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-x+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-3+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-7+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-dpad-left+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-input-mode "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::green "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+any-release-behavior+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::red-bits "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::blue "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+red-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-y+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-4+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-8+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-dpad-right+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-joystick-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::size "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+apientry-defined+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::refresh-rate "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+refresh-rate+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-z+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-5+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-9+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-dpad-up+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-joystick-user-pointer "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-gamma-ramp "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+api-unavailable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+release+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+lock-key-mods+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-6+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-a+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-guide+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-key-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-input-mode "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+arrow-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+release-behavior-flush+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+lose-context-on-reset+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-7+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-apostrophe+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-last+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-monitor-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-joystick-axes "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+auto-iconify+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-monitor-user-pointer "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-joystick-buttons "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+release-behavior-none+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+maximized+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-8+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-b+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-left-bumper+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-joystick-guid "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+aux-buffers+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-mouse-button-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-joystick-hats "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::blue-bits "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+repeat+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mod-alt+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-9+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-backslash+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-left-thumb+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-joystick-name "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+blue-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-scroll-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-joystick-user-pointer "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+resizable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mod-caps-lock+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-add+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-backspace+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-right-bumper+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+center-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-time "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-key "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+resize-all-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mod-control+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-decimal+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-c+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-right-thumb+
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+client-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-key-name "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+resize-ew-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mod-num-lock+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-divide+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-caps-lock+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-aspect-ratio "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-square+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cocoa-chdir-resources+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-key-scancode "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-attrib "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+resize-nesw-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mod-shift+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-enter+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-comma+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-start+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cocoa-frame-name+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-close-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitor-content-scale "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+resize-ns-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mod-super+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-equal+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-d+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-triangle+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cocoa-graphics-switching+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitor-name "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-content-scale-callback
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+resize-nwse-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-1+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-multiply+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-delete+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-x+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cocoa-menubar+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-focus-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitor-physical-size "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+samples+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-2+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-kp-subtract+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-down+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+gamepad-button-y+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cocoa-retina-framebuffer+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitor-pos "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-icon "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::green-bits "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitor-user-pointer "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+scale-to-monitor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-3+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-l+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-e+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+green-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+connected+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitor-workarea "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-iconify-callback
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-monitors "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+srgb-capable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-4+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-last+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-end+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hand-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-creation-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-maximize-callback
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-mouse-button "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+stencil-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-5+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-left+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-enter+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-monitor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-centered+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-debug+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-platform "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-primary-monitor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+stereo+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-6+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-left-alt+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-equal+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-opacity "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-down+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-no-error+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-pos "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+sticky-keys+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-7+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-left-bracket+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-escape+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-left+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-release-behavior+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-proc-address "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-pos-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::uint32-t "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+sticky-mouse-buttons+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-8+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-left-control+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-left-down+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-revision+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-required-instance-extensions
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-refresh-callback
          "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-time "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+transparent-framebuffer+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-last+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-left-shift+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f1+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-should-close "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-left-up+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-robustness+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::uint64-t "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-size "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-timer-frequency "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+true+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-left+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-left-super+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f10+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-right+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-version-major+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-timer-value "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-size-callback "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+version-major+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-middle+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-m+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f11+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-right-down+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+context-version-minor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+version-minor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-button-right+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-menu+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f12+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-right-up+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+crosshair-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-version "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-version-string "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+version-revision+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+mouse-passthrough+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-minus+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f13+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hat-up+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-size-limits "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-title "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-video-mode "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+version-unavailable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+native-context-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-n+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f14+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hovered+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::set-window-user-pointer "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cursor-captured+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-video-modes "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::show-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+visible+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+not-allowed-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-num-lock+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f15+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+hresize-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::swap-buffers "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-attrib "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cursor-disabled+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-content-scale "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+vresize-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+not-initialized+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-o+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f16+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+ibeam-cursor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::swap-interval "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cursor-hidden+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::terminate "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+wayland-app-id+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+no-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-p+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f17+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+iconified+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::update-gamepad-mappings "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cursor-normal+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::vulkan-supported "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+wayland-disable-libdecor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+no-current-context+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-page-down+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f18+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+invalid-enum+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::wait-events "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-frame-size "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+cursor-unavailable+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-monitor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+wayland-libdecor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+no-error+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-page-up+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f19+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+invalid-value+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::wait-events-timeout "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-opacity "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+decorated+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::window-hint "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-pos "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+wayland-prefer-libdecor+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+no-reset-notification+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-pause+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f2+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-1+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::window-hint-string "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-size "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+depth-bits+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::window-should-close "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::get-window-user-pointer "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+win32-keyboard-menu+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+no-robustness+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-period+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f20+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-10+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::hide-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+disconnected+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::iconify-window "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+x11-class-name+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+no-window-context+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-print-screen+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f21+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-11+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::init "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+dont-care+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+glfwapi+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+x11-instance-name+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-any-profile+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-q+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f22+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-12+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wcursor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+doublebuffer+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wimage "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+x11-xcb-vulkan-surface+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-r+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f23+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wmonitor "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-13+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::allocate "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+egl-context-api+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wwindow "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::reallocate "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+opengl-compat-profile+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-right+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+key-f24+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wgamepadstate "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+joystick-14+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::deallocate "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::+false+ "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::glf-wgammaramp "CLAW-CXX-GLFW3")
  (export 'claw-cxx-glfw3::user "CLAW-CXX-GLFW3"))

